#!/usr/bin/env python3

import click

@click.command()
@click.argument('notes_in', nargs=-1, type=int)
@click.option('-s', '--sep', default='\n', help='the separator delimiter')
@click.option('-m', '--modulus', default=12, help='the modulus to apply', type=int)
def keymod(notes_in, sep, modulus):
    if not len(notes_in):
        notes_in = [int(_) for _ in input().split()]

    out = [note % modulus for note in notes_in]

    print(*out, sep=sep)


if __name__ == '__main__':
    keymod()
