#!/usr/bin/env python3

"""
pnote / pitch to note converter
"""

__author__ = 'John Harrington'
__version__ = '1.0.0'

import sndalgo.pitch as pitch
import click

@click.command()
@click.argument('notes', type=float, nargs=-1)
@click.option('-s', '--sep', default='\n', type=str, help='separator for output')
def pnote(notes, sep):
    if not len(notes):
        notes = [int(note) for note in input().split()]

    notes = [pitch.note_str(note) for note in notes]

    print(*notes, sep=sep)

if __name__ == '__main__':
    pnote()
