#!/usr/bin/env python3

import sndalgo.waves as W

import click
import numpy as np

@click.command()
@click.argument('harmonics', nargs=-1, type=float)
@click.argument('block_size', type=int)
@click.option('-f', '--freq', type=float, help='the period of a full cycle of the wave', default=1.)
def synadd(harmonics, block_size, freq):
    harms = list(harmonics)

    if len(harms):
        wt = W.additive(harms, np.arange(block_size), block_size)

        [print(x) for x in W.lookup_oscil(freq, np.arange(block_size), wt, block_size)]

    else:
        print('ehh.. try again')


if __name__ == '__main__':
    synadd()
